Redesign `Display` derive macro
JelteF/derive_more pull request #225
Opened 2022-11-18 10:29 UTC by ilslv

Resolves #142, #217 

## Synopsis

## Solution

1. Use expressions instead of string literals for fmt arguments: 
   `#[display("{}", "crab.rave()")]` -> `#[display("{}", crab.rave())]`
2. Reimagine affix usage: TODO

## Checklist

- [ ] Documentation is updated (if required)
- [ ] Tests are added/updated (if required)
- [ ] [CHANGELOG entry][l:1] is added (if required)

[l:1]: /CHANGELOG.md

2022-11-18 11:44 UTC, ilslv commented
@tyranron @JelteF so we are on the same page, let me go over design decisions, that are already set in stone, before final decision on #142 is made.

This should cover ***every*** possible use-case, everything else should result in compile-time error. For example:

```rust
#[derive(Display)]
#[display("Field: {}")] // error: 1 positional argument in format string, but no arguments were given
struct Single(i32);
```

# Structs

## Unit

```rust
#[derive(Display)]
struct Unit; // "Unit"

#[derive(Display)]
struct Tuple (); // "UnitTuple"

#[derive(Display)]
struct Struct {} // "UnitStruct"
```

## Single-field

```rust
#[derive(Display)]
struct Tuple(i32); // "1"

#[derive(Display)]
struct Struct { field: i32 } // "1"

#[derive(Display)]
#[display("Pre: {_0}")]
struct PreTuple(i32); // "Pre: 1"

#[derive(Display)]
#[display("Pre: {field}")]
struct PreStruct { field: i32 } // "Pre: 1"
```

## Multi-field

```rust
#[derive(Display)]
#[display("{_0} {ident} {_1} {} {}", _1, any_expr(_0, _1), ident = 123, _1 = _0)]
struct Tuple(i32, i32) // "1 123 1 2 3"

#[derive(Display)]
#[display("{field1} {ident} {field2} {} {}", field2, any_expr(_0, _1), ident = 123, field2 = field1)]
struct Struct { field1: i32, field2: i32 } // "1 123 1 2 3"
```

# Enums

## Without variants (Infallible-like)

```rust
#[derive(Display)]
enum Void {}

const fn has<T: Display>() {}
const _ = has::<Void>();
```

## Unit variant

```rust
#[derive(Display)]
enum Enum {
    First, // "First"
    FirstTuple(), // "FirstTuple"
    FirstStruct {}, // "FirstStruct"
    #[display("SECOND")]
    Second, // "SECOND"
    #[display("SECOND_TUPLE")]
    SecondTuple(), // "SECOND_TUPLE"
    #[display("SECOND_STRUCT")]
    SecondStruct {}, // "SECOND_STRUCT"
}
```

## Single-field variant

```rust
#[derive(Display)]
enum Enum {
    First(i32), // "1"
    FirstNamed  { field: i32 }, // "1"
    #[display("Second: {_0}")]
    Second(i32), // "Second: 1"
    #[display("Second: {field}")]
    SecondNamed { field: i32 }, // "Second: 1"
}
```

## Multi-field variant

```rust
#[derive(Display)]
enum Enum {
    #[display("{_0} {ident} {_1} {} {}", _1, any_expr(_0, _1), ident = 123, _1 = _0)]
    Tuple(i32, i32), // "1 123 1 2 3"
    #[display("{field1} {ident} {field2} {} {}", field2, any_expr(_0, _1), ident = 123, field2 = field1)]
    Struct { field1: i32, field2: i32 }, // "1 123 1 2 3"
}
```

## Interactions with top-level attribute

TODO: Fill out, once #142 is resolved

# Unions

```rust
#[derive(Display)]
#[display("No field accesses are allowed, but {} is ok", "interpolation")]
union Union { // No field accesses are allowed, but interpolation is ok
    field: i32,
}
```

# Unresolved questions

Should we support `{0}` syntax in addition/instead of `{_0}`. `thiserror` does that.
Personally, I'm in favour of this feature in addition to legacy syntax. I think we can even emit deprecated warnings on them.

2022-11-18 12:18 UTC, ilslv commented
Discussed with @tyranron: Merge this PR without support for top-level enum attribute and do it as a separate PR.

2022-11-18 12:44 UTC, tyranron commented
@ilslv @JelteF one thing I still dislike is semantics for unit types:
```rust
#[derive(Display)]
struct Unit; // "Unit"

#[derive(Display)]
struct Tuple (); // "UnitTuple"

#[derive(Display)]
struct Struct {} // "UnitStruct"

#[derive(Display)]
enum Enum {
    First, // "First"
    FirstTuple(), // "FirstTuple"
    FirstStruct {}, // "FirstStruct"
}
```

This is too subtle and implicit. And may be too unexpected if I write `derive(Octal)` or similar.

I think it's better to return error in such cases, pushing a user to explicitly specify what he wants. Giving a convenient top-level attribute semantics, there would be almost no ergonomics impact if needs exactly this behaviour:
```rust
#[derive(Debug, Display)]
#[display("{self:?}")]
struct Unit; // "Unit"

#[derive(Debug, Display)]
#[display("{self:?}")]
struct Tuple (); // "Tuple"

#[derive(Debug, Display)]
#[display("{self:?}")]
struct Struct {} // "Struct"

#[derive(Debug, Display)]
#[display("{self:?}")]
enum Enum {
    First, // "Enum::First"
    FirstTuple(), // "Enum::FirstTuple"
    FirstStruct {}, // "Enum::FirstStruct"
}
```

But I would argue that most of the time, a user doesn't expect something `Debug`-like on `Display`ing unit types.

2022-11-18 13:03 UTC, ilslv commented
@tyranron 

> This is too subtle and implicit. And may be too unexpected if I write derive(Octal) or similar.

Valid point, if something like this exists, it should be only for `Display`.

---

I want to explain, why I've added this behaviour in a first place. 
From my personal experience, it's very unpleasant to write something like this by hand:

```rust
// #[derive(Display)]
enum Enum {
    A, 
    B,
    C,
}

impl fmt::Display for Enum {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::A => "A".fmt(f),
            Self::B => "B".fmt(f),
            Self::C => "B".fmt(f),
        }
    }
}
```

This is a lot of tedious code to write and copy-pasting may lead to errors. Have you noticed, that code block above contains an error?

I consider this feature desired, understandable and easily **discoverable** just by writing code without looking into the docs. Emphasis on **discoverable**, because this is one of the most delightful features of Rust to me. Discoverable intuitive design with compile-time checks is a match made in heaven. I don't think you can misinterpret it and your suggested approach doesn't cover this use-case. 
For unit structs this feature is less desirable, but I would add it just for symmetry. `#[display("{self:?}")]` looks really scary and something like only maintainer with a deep knowledge of this crate will use 🙃

2022-11-18 14:05 UTC, tyranron commented
@ilslv 

> `#[display("{self:?}")]` looks really scary and something like only maintainer with a deep knowledge of this crate will use 🙃

Isn't this the first thing a rustacean would try (or write manually) when he thinks about "`Display` as `Debug`" semantics?

> I don't think you can misinterpret it 

I do think such a feature implicitly pushes a library user to mix `Display`/`Debug` semantics, which is usually not a good idea. Given that most use-cases of this macro, in practice, is defining custom error types, I would prefer a compilation error about forbidden error description, rather than implicitly making it `Debug`-like.

> and your suggested approach doesn't cover this use-case.

Ah, you're talking more about [`strum::Display` semantics](https://docs.rs/strum/0.24/strum/derive.Display.html), rather than "`Display` as `Debug`" semantics, so we can replace `strum::Display` with `derive_more::Display` naturally. Now, what you're talking about makes much more sense. 🤔

Yeah, restricting it to `Display` only, has sense. But I would like to hear other opinions as well.  
ack @JelteF @ModProg

2022-11-18 14:12 UTC, ilslv commented
@tyranron 

> Isn't this the first thing a rustacean would try (or write manually) when he thinks about "Display as Debug" semantics?

To be fair I didn't think about this possibility, when implementing this functionality. And even if I just wasn't thinking enough, this assumption applies only to experienced rustaceans, but this library isn't only for them with ~50k daily downloads. 

> Given that most use-cases of this macro, in practice, is defining custom error types

I wouldn't just jump to this assumption, especially when there is `thiserror`. General-purpose `Display`s should be at the same level of priority. 

> so we can replace strum::Display with derive_more::Display naturally

Exactly!

2022-11-18 14:18 UTC, tyranron commented
@ilslv 

> Exactly!

And then, we [want to play with casing](https://github.com/JelteF/derive_more/issues/216). Maybe we could opt-in this behaviour explicitly by specifying `#[display(rename_all = ...)]`?

2022-11-18 14:25 UTC, ilslv commented
@tyranron i meant out of "scope for this PR" 🤦‍♂️
But definitely would like to see that functionality.

2022-11-18 14:28 UTC, tyranron commented
@ilslv I'm not talking about customizing, but rather still giving options how we can deal with `Debug`-like defaults for units, which is in scope of this PR.

2022-11-18 15:10 UTC, ModProg commented
I'm not sure what the right default behavior is for derive Display. 

> @ilslv I'm not talking about customizing, but rather still giving options how we can deal with `Debug`-like defaults for units, which is in scope of this PR.
> 
> ```rust
> #[derive(Display)]
> #[display(rename_all = "upper")]
> enum Enum {
>     A,  // "A"
>     B,  // "B"
>     C,  // "C"
> }
> 
> #[derive(Display)]
> enum AnotherEnum {  // compilation error!
>     A, 
>     B, 
>     C, 
> }
> ```

The advantage of this behavior is, it removes any ambiguity on what the output is. Though, it would in my opinion make sense to adopt serde's casing for the `rename_all` to make it 100% clear what is happening: 
https://serde.rs/container-attrs.html#rename_all

> ### #[serde(rename_all = "...")]
> Rename all [...] variants [...] according to the given case convention. The possible values are "lowercase", "UPPERCASE", "PascalCase", "camelCase", "snake_case", "SCREAMING_SNAKE_CASE", "kebab-case", "SCREAMING-KEBAB-CASE".

We could also add a way to add something like `rename_all = "Debug"` but that is not necessarily better than just saying `{self:?}`

One thing I just thought about would be to somehow enable the renamed variant in the `default_format` of an enum, kind of like so:
```rs
#[display("{self:snake_case} {_0}")]
```
But that is probably a very niche feature, and not really worth increasing complexity for (only thought about it, because I'd have a use in a current project).

2022-11-18 15:15 UTC, ModProg commented
> To be fair I didn't think about this possibility, when implementing this functionality. And even if I just wasn't thinking enough, this assumption applies only to experienced rustaceans, but this library isn't only for them with ~50k daily downloads.

This should definitely be documented in the Display derive macro documentation, as I feel like this might be a generally quite useful usage.

2022-11-21 06:00 UTC, ilslv commented
@tyranron 

> ```rust
> #[derive(Display)]
> enum AnotherEnum {  // compilation error!
> ```

I vote against explicitly specifying `#[display(rename_all = "upper")]`. I don't think this gives us some value, only adds friction.

2022-11-21 19:12 UTC, JelteF commented
To be clear, I haven't yet looked at the code. I think the Unit enum stuff sounds useful, but shouldn't be part of this PR. Also introducing it doesn't break the Display derive API, so I don't think it should be part of the 1.0.0 milestone. I think we should move discussion about that feature to #216

2022-12-12 18:58 UTC, ModProg commented
@tyranron generally sound good, only thing it cannot unite is my "I want an error when I forget to add a format to an enum Variant".

But that would've been a breaking change anyway.

2022-12-12 19:28 UTC, tyranron commented
@ModProg 

> only thing it cannot unite is my "I want an error when I forget to add a format to an enum Variant".

Why? Isn't this case about this?
```rust
#[derive(Error)] // look, ma! we don't need to specify obvious `Display` here
enum AnotherError {
    A,          // expansion error, as we forgot to specify error description here
    B(String),  // prints the inner string
}
```

Or you've meant any enum variant, not just a unit-like?

2022-12-12 20:52 UTC, ModProg commented
@tyranron yes, and my usecase wasn't an error. It was generating commands.

2022-12-13 13:35 UTC, ModProg commented
> Moreover I don't really think "forgetting to specify formatting" is a big deal. In this case error message may confuse you for a second, but code itself should help pin down the cause for an error.

Well if it is an error that is, in different usecases this might be a bigger issue.


But I do understand that for most users this is more convenient than requiring them always.

Maybe it could be a default-feature that can be disabled? But in the end, I'm fine with anything.

2022-12-19 00:23 UTC, JelteF commented
@tyranron While I agree that Error deriving display is more ergonomic, it's not in line with how derives normally work afaik. At least in the stdlib it's not how it works. `Eq` alse requires deriving `PartialEq`. Also, I think such a proposed subtle difference between how `derive(Error)` derives `Display` and how `derive(Display)` would cause confusion itself. Especially since (in your example at least), one uses `error(...)` while the other would use `display(...)` as the attribute.

After all this extra information and discussion, I'm now siding with @ilslv and I agree we should derive units by default.

2022-12-19 00:24 UTC, JelteF commented
> Maybe it could be a default-feature that can be disabled? But in the end, I'm fine with anything.

That seems like a non-breaking change (since it's opt-in), so I think we can postpone that decision until after 1.0

2022-12-20 09:05 UTC, tyranron commented
@JelteF thank you for the feedback. You and @ilslv convinced me that the current behaviour would be a lesser evil.

I'll review this PR shortly, so we can move towards  releasing 1.0.

2023-01-23 13:57 UTC, tyranron submitted a review, later dismissed
> I'll review this PR shortly.

> shortly

_shortly_™... 😅

@ilslv what an amazing work. Thanks!

I've adjusted docs a little and some local variables naming. Everything else seems good.

2023-01-23 14:40 UTC, tyranron commented
@JelteF would you like to take a look on this? Or we can merge it?

The CI issue is fixed in https://github.com/JelteF/derive_more/pull/231.

2023-01-23 16:11 UTC, JelteF commented
I merged #231 if this is rebased I guess CI should pass now. Feel free to merge it.

2023-01-23 17:59 UTC, ModProg requested changes

2023-01-23 17:59 UTC, ModProg commented on impl/doc/display.md
> +`#[display(bound(...))]` accepts a single string argument in a format similar to the format
I don't think it is a string anymore is it?

2023-01-24 12:24 UTC, tyranron approved these changes

2023-01-24 12:30 UTC, merged