allow custom format on item for Debug
JelteF/derive_more pull request #279
Opened 2023-07-25 16:26 UTC by ModProg

Resolves #277

## Synopsis

## Solution

## Checklist

- [ ] Documentation is updated (if required)
- [ ] Tests are added/updated (if required)
- [ ] [CHANGELOG entry][l:1] is added (if required)

[l:1]: /CHANGELOG.md

2023-07-26 12:34 UTC, tyranron commented
@ModProg @JelteF also, it's a bit unclear how it should work with the item-level formatting attributes?

```rust
#[derive(Debug)]
#[debug("{name}={value:?}")]
struct Arg {
  #[debug("{name}!")]
  name: String,
  value: String
}
```
What should happen here?
1. Compilation error saying that we cannot mix top-level and field-level formatting attributes.
2. Print `name!=value`, considering the field-level formatting in top-level attribute.
3. Print `name=value`, silently ignoring the field-level formatting.

I'd vote for the option 1.

2023-07-26 17:36 UTC, JelteF commented
> it's a bit unclear how it should work with the item-level formatting attributes?

I think option 1 seems good.

2023-07-26 17:38 UTC, ModProg commented
while 1. is definitly easier, 2. looks reasonable as well. but we can do that later, as it's a non breaking change.

2023-07-27 13:25 UTC, ModProg commented on tests/debug.rs
> +    }
Maybe it is even the other way round, format on the enum itself should probably match #142, meaning that this should only do variant formatting but not item formatting.

2023-07-28 11:35 UTC, tyranron commented on tests/debug.rs
> +    }
@ModProg yes... the top-level format attribute should be placed on the whole struct on structs, and on variants on enums (we see an enum as an enumeration of some structs), while disallowed on a whole enum.

2023-08-01 15:09 UTC, tyranron requested changes
@ModProg at the moment, trait bounds for type parameters are being inferred incorrectly when top-level attribute comes into play. I've added tests covering those situations.

2023-08-03 08:39 UTC, JelteF commented
> I've added tests covering those situations.

Somehow github is not showing them in this PR (but I see them on the branch on @ModProg their fork). I'm assuming the tests are not passing?

2023-08-03 09:07 UTC, ModProg commented
@JelteF @tyranron I added it to the bounds_generation. If a format argument is present for the container, its bounds replace the field bounds.

2023-08-04 16:39 UTC, tyranron approved these changes
@ModProg thank you! Very nice job and quite a thoughtful implementation! 👍

I've ripped some repeated parts a little bit more, though, and made some bikeshedings regarding errors terminology.

@JelteF would you like to take a look, or we can merge it?

2023-08-05 10:59 UTC, JelteF approved these changes

2023-08-05 11:04 UTC, merged

2023-08-07 09:47 UTC, tyranron commented
@JelteF could you make a `0.1.0-beta.3` release with fixes of recently merged PRs? I'd like to try it out on our codebase.

2023-08-07 11:08 UTC, JelteF commented
> could you make a 0.1.0-beta.3 release with fixes of recently merged PRs?

Done