feat(is_variant): add `#[must_use]` annotation
JelteF/derive_more pull request #350
Opened 2024-04-18 17:59 UTC by TheLostLambda

Resolves #349 

## Synopsis & Solution

Adds a `#[must_use]` annotation to the static methods generated by `IsVariant`.

## Checklist

- [ ] Documentation is updated (if required)
- [ ] Tests are added/updated (if required)

I'll be honest, I'm not 100% sure how to write tests for this one, but I have a screenshot of it in action:
![Screenshot from 2024-04-18 10-32-13](https://github.com/JelteF/derive_more/assets/6251883/0ac850b3-ddd0-4c5e-9037-baf56f96add4)

- [ ] [CHANGELOG entry][l:1] is added (if required)

[l:1]: /CHANGELOG.md

2024-04-18 19:28 UTC, tyranron requested changes
@TheLostLambda thanks for quick reaction! 

Let's add few bikesheddings and get it merged!

2024-04-18 19:28 UTC, tyranron commented on impl/src/is_variant.rs
> +                matches!(self, #enum_name ::#variant_ident #data_pattern)
For hygiene, this should be used like `derive_more::core::matches!`.

2024-04-18 19:28 UTC, tyranron commented on impl/doc/is_variant.md
>      pub const fn is_just(&self) -> bool {
I'm not sure whether we should make an accent on `#[inline]` in docs. Let's leave only `#[must_use]` in docs.

2024-04-18 19:28 UTC, tyranron commented on CHANGELOG.md
> +- Static methods derived by `IsVariant` are now marked `#[must_use]`.
It would be nice to also add the pull request reference, as is done below for some changes.

2024-04-18 19:32 UTC, tyranron commented
> I'll be honest, I'm not 100% sure how to write tests for this one, but I have a screenshot of it in action:
> ![Screenshot from 2024-04-18 10-32-13](https://private-user-images.githubusercontent.com/6251883/323710428-0ac850b3-ddd0-4c5e-9037-baf56f96add4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Njg4NjAsIm5iZiI6MTcxMzQ2ODU2MCwicGF0aCI6Ii82MjUxODgzLzMyMzcxMDQyOC0wYWM4NTBiMy1kZGQwLTRjNWUtOTAzNy1iYWY1NmY5NmFkZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMTkyOTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk0NjM4ZGJlMGE1M2M4MmZjZjFiMTc4ZGRiMGQyMTU0ZmVmZWI2NmFhYjFjMTUyMjFlYTY3ZjhhM2ZkYmY4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ex1i9IOXQ5-gRAwepWrAu0ZuDmOingmauquY9LDX6N4)

You can add `tests/compile_fail` with `#[deny(unused_must_use)]`. So if this will be removed in future, the test case will compile successfully, and so, fail the test.

2024-04-18 19:33 UTC, TheLostLambda commented
@tyranron Ah! Excellent! The `tests/compile_fail` is exactly what I was looking for!

I'll get to work addressing these loose ends!

2024-04-18 20:14 UTC, TheLostLambda commented
I just went a little insane trying to figure out why those tests we're running for me, but it seems the compile fail tests are all disabled on nightly Rust (only running for stable).

I think that means all of these tests are missed by CI as well, since there are a couple of failing tests unrelated to my change here.

Would you like me to add something to the CI in this PR or remove that stable-only attribute? I assume that was added in the first place to stop things from breaking when the nightly and stable compilers gave different errors, so perhaps just adding a bit in the CI is the best thing to do?

2024-04-18 20:38 UTC, TheLostLambda commented
Conclusion is that I have no idea why that last CI run didn't fail... It looks like things *are* being run in the `stable` `test` CI (one of the matrix options), but it passed in CI and failed for me, with exactly the same version of stable Rust?

I've pushed the changes that make things pass for me locally, so maybe those will break the CI version? They should?

TL;DR is that I think I've addressed all of your comments, but, unrelated, I'm not sure if the `compile_fail` tests are working correctly either in CI or on my machine...

2024-04-19 14:50 UTC, tyranron approved these changes
@TheLostLambda this is just some platform-dependent output weirdness.

Overall, now it's LGTM. Thanks!

2024-04-19 14:53 UTC, merged